# main text of home
name: ietsism
title: ietsism
bio: Serendipity is crucial because it expands your horizons - <i>Cass Sunstein</i>

# twitter summary info
description: A blog about anything that occupies my mind

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url:

url: https://www.ietsism.net
repository: ietsism/ietsism.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-78029607-3'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: ietsism # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: ietsism
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
medium: ietsism
# vimeo: myvimeo
# lanyrd: mylanyrd
email: contact@ietsism.net

authors:
  ietsism:
    name: ietsism
    bio: A man who spends too much time online
    external-image: false
    picture: assets/images/profile.jpg

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: false

# do you want some animations?
animation: true


webp:
  enabled: true

  # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
  quality: 75

  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  # By default the generator will search for a folder called `/img` under the site root and process all jpg, png and tiff image files found there.
  img_dir: ["/assets/images/posts/"]

  # Whether to search in nested directories or not
  nested: true

  # add ".gif" to the format list to generate webp for animated gifs as well
  formats: [".jpeg", ".jpg", ".png", ".tiff"]

  # File extensions for animated gif files
  gifs: [".gif"]

  # Set to true to always regenerate existing webp files
  regenerate: false

  # Local path to the WebP utilities to use (relative or absolute)
  # Omit or leave as nil to use the utilities shipped with the gem, override only to use your local install
  webp_path: nil

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false
  -
    scope:
      path:            "projects.html"
    values:
      sitemap:         false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-email-protect
  - jemoji
  - jekyll-target-blank
  - jekyll-webp
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-minifier

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "travis.sh",
    "ideas.md",
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "node_modules",
    "vendor",
    "CNAME",
    "Rakefile",
    "script/",
  ]
